### PR TITLE
Get HAPI datasets and resources

### PR DESCRIPTION
**Pull request by mcarans**
Scraper framework now supplies get_hapi_metadata which gives datasets abd resources for DB
However I don't knwo how to supply git+ssh://git@github.com/OCHA-DAP/hdx-python-scraper@hapi_metadata#egg=hdx-python-scraper in pyproject.toml so that pre-commit works

### CODE REVIEW

**Review by turnerm — APPROVED** [review]
Looks good to me, but I don't quite understand your question, could you elaborate?

**Comment by mcarans** [comment]
The changes I have made to HDX Python Scraper are in a branch and I would like to make a requirement on `git+ssh://git@github.com/OCHA-DAP/hdx-python-scraper@hapi_metadata#egg=hdx-python-scraper` while I continue to modify HDX Python Scraper. When I run pre-commit with something like the above in pyproject.toml under dependencies, it gives an error. I guess I must not have the format right for pyproject.toml or something like that

**Comment by turnerm** [comment]
@mcarans ah I see, looking into a bit too. Did you manage to find a format that works with `pip install .?`

**Comment by mcarans** [comment]
@turnerm The format `git+ssh://git@github.com/OCHA-DAP/hdx-python-scraper@hapi_metadata#egg=hdx-python-scraper` works in requirements.txt.

**Comment by mcarans** [comment]
I had to set Hatch configuration
```
[tool.hatch.metadata]
allow-direct-references = true
```
However, PyCharm has a [bug](https://youtrack.jetbrains.com/issue/PY-60239/Package-requirement-unsatisfied-when-pointing-to-a-git-repo) so have to manually install requirements.txt: `pip install -r requirements.txt`

**Comment by turnerm** [comment]
Nice find! Looks good to me

**Pull request merged**
